apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-app
  labels:
    app: cal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cal
  template:
    metadata:
      labels:
        app: cal
    spec:
      containers:
        - name: cal
          image: shariq27/cal-app
          ports:
            - containerPort: 3040
