apiVersion: v1
kind: Service
metadata:
  name: cal-service
  labels:
    app: cal
spec:
  selector:
    app: cal
  ports:
    - protocol: TCP
      port: 3040
      targetPort: 3040
  type: LoadBalancer